### ISSUE TITLE
ElasticSearch 6.3 compatibility

### ISSUE THREAD

**Issue by mattiasarro** [alexklibisz/approximate-vector-search#6]
When trying to install the plugin on ES 6.3 (as opposed to 6.2), I get the following error:

```
[root@942d318f5cb4 aknn]# elasticsearch-plugin install -b file:build/distributions/elasticsearch-aknn-0.0.1-SNAPSHOT.zip
-> Downloading file:build/distributions/elasticsearch-aknn-0.0.1-SNAPSHOT.zip
[=================================================] 100%??
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.
```

I haven't found what changes are needed for making this plugin work with ES 6.3. Any suggestions?

**Comment by alexklibisz** [comment]
I'm not entirely sure either. As a first pass maybe try updating all of the 6.2 versions to 6.3 in build.gradle?

**Comment by mattiasarro** [comment]
There were a few other things that needed changing, but [managed to upgrade to 6.3.2](https://github.com/mattiasarro/elastik-nearest-neighbors/commit/cd54876f3cbb886d00f243a2368b1c0996f64500).
